import { AuditCategory } from "@/generated/prisma/client";
import type { AuditActionType } from "./audit-actions";

const actionCategoryMap: Record<AuditActionType, AuditCategory> = {
  USER_ACCOUNT_CREATED: AuditCategory.SECURITY,
  USER_ACCOUNT_UPDATED: AuditCategory.SECURITY,
  USER_ACCOUNT_UPDATED_WITH_PERMISSIONS: AuditCategory.SECURITY,
  USER_ACCOUNT_DELETED: AuditCategory.SECURITY,
  USER_ACCOUNT_ACTIVATED: AuditCategory.SECURITY,
  USER_ACCOUNT_DEACTIVATED: AuditCategory.SECURITY,
  USER_PROFESSIONAL_DOC_ADDED: AuditCategory.SECURITY,
  USER_PROFESSIONAL_DOC_REVOKED: AuditCategory.SECURITY,
  ROLE_CREATED: AuditCategory.SECURITY,
  ROLE_UPDATED: AuditCategory.SECURITY,
  ROLE_DELETED: AuditCategory.SECURITY,
  ROLE_PERMISSIONS_CHANGED: AuditCategory.SECURITY,
  USER_ROLE_ASSIGNED: AuditCategory.SECURITY,
  USER_ROLE_REMOVED: AuditCategory.SECURITY,
  USER_PERMISSION_OVERRIDE: AuditCategory.SECURITY,

  STOCK_RECEIPT_REGISTERED: AuditCategory.BUSINESS,
  STOCK_CONSUMPTION_RECORDED: AuditCategory.BUSINESS,
  STOCK_TRANSFER_COMPLETED: AuditCategory.BUSINESS,
  STOCK_MANUAL_ADJUSTMENT: AuditCategory.BUSINESS,
  STOCK_RESERVATION_PLACED: AuditCategory.BUSINESS,
  STOCK_RESERVATION_RELEASED: AuditCategory.BUSINESS,
  STOCK_BATCH_QUARANTINED: AuditCategory.BUSINESS,
  STOCK_BATCH_RELEASED: AuditCategory.BUSINESS,
  STOCK_BATCH_EXPIRED: AuditCategory.BUSINESS,
  ITEM_REQUEST_SUBMITTED: AuditCategory.BUSINESS,
  ITEM_REQUEST_APPROVED: AuditCategory.BUSINESS,
  ITEM_REQUEST_REJECTED: AuditCategory.BUSINESS,
  ITEM_REQUEST_FULFILLED: AuditCategory.BUSINESS,
  ITEM_REQUEST_CANCELLED: AuditCategory.BUSINESS,

  FACILITY_CONFIG_UPDATED: AuditCategory.GOVERNANCE,
  LOCATION_CONFIG_UPDATED: AuditCategory.GOVERNANCE,
  INVENTORY_LIMITS_CHANGED: AuditCategory.GOVERNANCE,
  SYSTEM_SETTINGS_CHANGED: AuditCategory.GOVERNANCE,
  BULK_DATA_IMPORTED: AuditCategory.GOVERNANCE,
  BULK_DATA_EXPORTED: AuditCategory.GOVERNANCE,

  USER_SENSITIVE_DATA_VIEWED: AuditCategory.SENSITIVE_ACCESS,
  PROFESSIONAL_DOC_EXPOSED: AuditCategory.SENSITIVE_ACCESS,
  FINANCIAL_COST_EXPOSED: AuditCategory.SENSITIVE_ACCESS,
};

export function getCategoryForAction(action: string): AuditCategory {
  return (actionCategoryMap as Record<string, AuditCategory>)[action] ?? AuditCategory.BUSINESS;
}
