export const AuditAction = {
  USER_ACCOUNT_CREATED: "USER_ACCOUNT_CREATED",
  USER_ACCOUNT_UPDATED: "USER_ACCOUNT_UPDATED",
  USER_ACCOUNT_UPDATED_WITH_PERMISSIONS: "USER_ACCOUNT_UPDATED_WITH_PERMISSIONS",
  USER_ACCOUNT_DELETED: "USER_ACCOUNT_DELETED",
  USER_ACCOUNT_ACTIVATED: "USER_ACCOUNT_ACTIVATED",
  USER_ACCOUNT_DEACTIVATED: "USER_ACCOUNT_DEACTIVATED",

  USER_PROFESSIONAL_DOC_ADDED: "USER_PROFESSIONAL_DOC_ADDED",
  USER_PROFESSIONAL_DOC_REVOKED: "USER_PROFESSIONAL_DOC_REVOKED",

  ROLE_CREATED: "ROLE_CREATED",
  ROLE_UPDATED: "ROLE_UPDATED",
  ROLE_DELETED: "ROLE_DELETED",
  ROLE_PERMISSIONS_CHANGED: "ROLE_PERMISSIONS_CHANGED",

  USER_ROLE_ASSIGNED: "USER_ROLE_ASSIGNED",
  USER_ROLE_REMOVED: "USER_ROLE_REMOVED",
  USER_PERMISSION_OVERRIDE: "USER_PERMISSION_OVERRIDE",

  STOCK_RECEIPT_REGISTERED: "STOCK_RECEIPT_REGISTERED",
  STOCK_CONSUMPTION_RECORDED: "STOCK_CONSUMPTION_RECORDED",
  STOCK_TRANSFER_COMPLETED: "STOCK_TRANSFER_COMPLETED",
  STOCK_MANUAL_ADJUSTMENT: "STOCK_MANUAL_ADJUSTMENT",
  STOCK_RESERVATION_PLACED: "STOCK_RESERVATION_PLACED",
  STOCK_RESERVATION_RELEASED: "STOCK_RESERVATION_RELEASED",

  STOCK_BATCH_QUARANTINED: "STOCK_BATCH_QUARANTINED",
  STOCK_BATCH_RELEASED: "STOCK_BATCH_RELEASED",
  STOCK_BATCH_EXPIRED: "STOCK_BATCH_EXPIRED",

  ITEM_REQUEST_SUBMITTED: "ITEM_REQUEST_SUBMITTED",
  ITEM_REQUEST_APPROVED: "ITEM_REQUEST_APPROVED",
  ITEM_REQUEST_REJECTED: "ITEM_REQUEST_REJECTED",
  ITEM_REQUEST_FULFILLED: "ITEM_REQUEST_FULFILLED",
  ITEM_REQUEST_CANCELLED: "ITEM_REQUEST_CANCELLED",

  FACILITY_CONFIG_UPDATED: "FACILITY_CONFIG_UPDATED",
  LOCATION_CONFIG_UPDATED: "LOCATION_CONFIG_UPDATED",
  INVENTORY_LIMITS_CHANGED: "INVENTORY_LIMITS_CHANGED",
  SYSTEM_SETTINGS_CHANGED: "SYSTEM_SETTINGS_CHANGED",
  BULK_DATA_IMPORTED: "BULK_DATA_IMPORTED",
  BULK_DATA_EXPORTED: "BULK_DATA_EXPORTED",

  USER_SENSITIVE_DATA_VIEWED: "USER_SENSITIVE_DATA_VIEWED",
  PROFESSIONAL_DOC_EXPOSED: "PROFESSIONAL_DOC_EXPOSED",
  FINANCIAL_COST_EXPOSED: "FINANCIAL_COST_EXPOSED",
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];
